const SITE='https://akbmusix.pages.dev';
const TYPES=['Song Request','Lyrics Correction','Chords Correction','Tutorial Request','Cover Suggestion','General Advice / Suggestion'];
const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const clean=(v,max=1000)=>String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s{3,}/g,'  ').trim().slice(0,max);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugify=v=>clean(v,120).toLowerCase().normalize('NFKD').replace(/[^a-z0-9\u0980-\u09ff]+/g,'-').replace(/^-|-$/g,'');
async function hash(value){const b=await crypto.subtle.digest('SHA-256',enc.encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function fingerprint(request,body){const token=clean(request.headers.get('x-device-id'),100);const ip=request.headers.get('cf-connecting-ip')||'unknown';return hash(`${token||'none'}|${ip}|${body}`);}
async function body(request){try{return await request.json();}catch{return {};}}
async function recentBlock(db,table,fp,seconds){const row=await db.prepare(`SELECT COUNT(*) count FROM ${table} WHERE fingerprint=? AND created_at > datetime('now', ?)`).bind(fp,`-${seconds} seconds`).first();return Number(row?.count)>0;}
function cookie(request,name){return request.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)||'';}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode(value));return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/=+$/,'');}
async function isAdmin(request,env){if(!env.ADMIN_SESSION_SECRET)return false;const raw=cookie(request,'akb_admin');const [exp,sig]=raw.split('.');if(!exp||Number(exp)<Date.now())return false;return sig===await sign(exp,env.ADMIN_SESSION_SECRET);}
const requireAdmin=async(request,env)=>await isAdmin(request,env)?null:json({error:'Unauthorized'},401);
function parseMedia(value){try{const arr=typeof value==='string'?JSON.parse(value):value;return Array.isArray(arr)?arr.slice(0,20).map(m=>({type:clean(m.type,40),platform:clean(m.platform,20),label:clean(m.label,100),url:safeUrl(m.url)})).filter(m=>m.url):[];}catch{return [];}}
function safeUrl(v){try{const u=new URL(clean(v,500));return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function publicSong(row){return {...row,key:row.song_key,lyrics:String(row.lyrics||'').replace(/\\n/g,'\n'),chords:String(row.chords||'').replace(/\\n/g,'\n'),featured:Boolean(row.featured),media:parseMedia(row.media_json)};}
async function getSong(db,slug,admin=false){return db.prepare(`SELECT * FROM songs WHERE slug=? ${admin?'':"AND status='published'"}`).bind(slug).first();}
function page(title,description,canonical,content,jsonLd='',robots='index,follow'){
 return `<!doctype html><html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${robots}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css">${jsonLd?`<script type="application/ld+json">${jsonLd.replace(/</g,'\\u003c')}</script>`:''}</head><body>${content}</body></html>`;
}
function mediaLinks(items){if(!items.length)return '';return `<section class="media-box"><h2>ভিডিও ও লিংক</h2><div class="media-list">${items.map(m=>`<a class="media-link" href="${esc(m.url)}" target="_blank" rel="noopener noreferrer"><span><strong>${esc(m.type||m.label)}</strong><small>${esc(m.platform)}</small></span><span aria-hidden="true">↗</span></a>`).join('')}</div></section>`;}
async function songPage(env,slug){const row=await getSong(env.DB,slug);if(!row)return new Response('Not found',{status:404});const s=publicSong(row);const title=s.seo_title||`${s.title} Lyrics & Chords | AKBmusix`;const description=s.meta_description||`${s.title} by ${s.artist}. Lyrics, chords, key, capo and tutorials.`;const canonical=`${SITE}/songs/${s.slug}/`;const related=await env.DB.prepare("SELECT title,slug,artist FROM songs WHERE status='published' AND id<>? ORDER BY CASE WHEN artist_slug=? THEN 0 WHEN language=? THEN 1 ELSE 2 END, featured DESC, updated_at DESC LIMIT 6").bind(s.id,s.artist_slug,s.language).all();const comments=await env.DB.prepare("SELECT id,name,comment,created_at FROM comments WHERE song_id=? AND status='approved' ORDER BY created_at DESC LIMIT 50").bind(s.id).all();const rating=await env.DB.prepare('SELECT ROUND(AVG(rating),1) average, COUNT(*) count FROM ratings WHERE song_id=?').bind(s.id).first();const ld=JSON.stringify({'@context':'https://schema.org','@type':'MusicComposition',name:s.title,composer:{'@type':'Person',name:s.artist},inLanguage:s.language,url:canonical});const payload=esc(JSON.stringify({...s,comments:comments.results,rating}));const content=`<header class="site-header"><a class="brand" href="/">AKBmusix</a><nav><a href="/#songs">গান</a><a href="/#request">অনুরোধ</a><a href="/about.html">পরিচিতি</a></nav></header><main class="song-page"><a class="back" href="/">← সব গান</a><article id="songRoot" data-song="${payload}"><h1 class="song-title">${esc(s.title)}</h1><p class="song-meta"><a href="/artists/${esc(s.artist_slug)}/">${esc(s.artist)}</a> · Key ${esc(s.song_key)} · ${esc(s.capo)} · ${esc(s.language)}</p><div class="empty">গান প্রস্তুত হচ্ছে...</div></article>${mediaLinks(s.media)}<section class="related"><h2>সম্পর্কিত গান</h2><div class="song-grid">${related.results.map(r=>`<a class="song-card" href="/songs/${esc(r.slug)}/"><h3>${esc(r.title)}</h3><p>${esc(r.artist)}</p></a>`).join('')||'<p class="muted">আরও গান শিগগিরই যোগ হবে।</p>'}</div></section></main><footer>© AKBmusix</footer><script src="/song.js" defer></script>`;return new Response(page(title,description,canonical,content,ld),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=60'}});}
async function artistPage(env,slug){const songs=await env.DB.prepare("SELECT title,slug,artist,language,song_key,capo FROM songs WHERE artist_slug=? AND status='published' ORDER BY title").bind(slug).all();if(!songs.results.length)return new Response('Not found',{status:404});const artist=songs.results[0].artist;const canonical=`${SITE}/artists/${slug}/`;const content=`<header class="site-header"><a class="brand" href="/">AKBmusix</a></header><main class="section"><a class="back" href="/">← সব গান</a><h1>${esc(artist)}</h1><p class="muted">${songs.results.length}টি প্রকাশিত গান</p><div class="song-grid">${songs.results.map(s=>`<a class="song-card" href="/songs/${esc(s.slug)}/"><h2>${esc(s.title)}</h2><p>${esc(s.language)} · Key ${esc(s.song_key)} · ${esc(s.capo)}</p></a>`).join('')}</div></main>`;return new Response(page(`${artist} Songs, Lyrics & Chords | AKBmusix`,`${artist}-এর প্রকাশিত গান, লিরিক্স ও কর্ডস।`,canonical,content));}

async function api(request,env,path){
 const method=request.method;
 if(path==='/api/songs'&&method==='GET'){const q=clean(new URL(request.url).searchParams.get('q'),100).toLowerCase();const rows=await env.DB.prepare("SELECT id,title,slug,artist,artist_slug,language,category,song_key,capo,tempo,strumming,lyrics,chords,tags,featured FROM songs WHERE status='published' ORDER BY featured DESC, updated_at DESC").all();return json(rows.results.map(publicSong).filter(s=>!q||`${s.title} ${s.artist} ${s.lyrics} ${s.chords} ${s.tags}`.toLowerCase().includes(q)));}
 if(path.match(/^\/api\/songs\/[^/]+$/)&&method==='GET'){const row=await getSong(env.DB,decodeURIComponent(path.split('/').pop()));return row?json(publicSong(row)):json({error:'Not found'},404);}
 if(path.match(/^\/api\/songs\/[^/]+\/comments$/)&&method==='POST'){const p=await body(request),slug=decodeURIComponent(path.split('/')[3]),song=await getSong(env.DB,slug);if(!song)return json({error:'Song not found'},404);const comment=clean(p.comment,800),name=clean(p.name,60)||'Anonymous';if(comment.length<2)return json({error:'Comment is required'},400);const fp=await fingerprint(request,'comment');if(await recentBlock(env.DB,'comments',fp,30))return json({error:'Please wait before submitting again'},429);await env.DB.prepare('INSERT INTO comments(song_id,name,comment,fingerprint) VALUES(?,?,?,?)').bind(song.id,name,comment,fp).run();return json({ok:true,message:'Comment submitted for approval'},201);}
 if(path.match(/^\/api\/songs\/[^/]+\/rating$/)&&method==='POST'){const p=await body(request),value=Number(p.rating),slug=decodeURIComponent(path.split('/')[3]),song=await getSong(env.DB,slug);if(!song)return json({error:'Song not found'},404);if(!Number.isInteger(value)||value<1||value>5)return json({error:'Rating must be 1 to 5'},400);const fp=await fingerprint(request,'rating');await env.DB.prepare("INSERT INTO ratings(song_id,fingerprint,rating) VALUES(?,?,?) ON CONFLICT(song_id,fingerprint) DO UPDATE SET rating=excluded.rating,updated_at=CURRENT_TIMESTAMP").bind(song.id,fp,value).run();const stats=await env.DB.prepare('SELECT ROUND(AVG(rating),1) average, COUNT(*) count FROM ratings WHERE song_id=?').bind(song.id).first();return json({ok:true,...stats});}
 if(path==='/api/requests'&&method==='POST'){const p=await body(request),message=clean(p.message,1200),type=clean(p.type,50);if(!message||!TYPES.includes(type))return json({error:'Valid type and message are required'},400);const url=p.relevantUrl?safeUrl(p.relevantUrl):'';if(p.relevantUrl&&!url)return json({error:'Relevant URL is invalid'},400);const fp=await fingerprint(request,'request');if(await recentBlock(env.DB,'requests',fp,45))return json({error:'Please wait before submitting again'},429);await env.DB.prepare('INSERT INTO requests(name,type,song_name,message,relevant_url,fingerprint) VALUES(?,?,?,?,?,?)').bind(clean(p.name,60)||'Anonymous',type,clean(p.songName,120),message,url,fp).run();return json({ok:true},201);}
 if(path==='/api/admin/login'&&method==='POST'){const p=await body(request);if(!env.ADMIN_PASSWORD||!env.ADMIN_SESSION_SECRET||clean(p.password,200)!==env.ADMIN_PASSWORD)return json({error:'Invalid password'},401);const exp=String(Date.now()+8*60*60*1000),sig=await sign(exp,env.ADMIN_SESSION_SECRET);return json({ok:true},200,{'set-cookie':`akb_admin=${exp}.${sig}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`});}
 if(path==='/api/admin/logout'&&method==='POST')return json({ok:true},200,{'set-cookie':'akb_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});
 if(path.startsWith('/api/admin/')){const denied=await requireAdmin(request,env);if(denied)return denied;
  if(path==='/api/admin/dashboard'&&method==='GET'){const stats=await env.DB.prepare("SELECT (SELECT COUNT(*) FROM songs) totalSongs,(SELECT COUNT(*) FROM comments) totalComments,(SELECT COUNT(*) FROM comments WHERE status='pending') pendingComments,(SELECT COUNT(*) FROM requests) totalRequests,(SELECT COUNT(*) FROM requests WHERE status='pending') pendingRequests,(SELECT ROUND(AVG(rating),1) FROM ratings) averageRatings").first();return json(stats);}
  if(path==='/api/admin/songs'&&method==='GET'){const rows=await env.DB.prepare('SELECT * FROM songs ORDER BY updated_at DESC').all();return json(rows.results.map(publicSong));}
  if(path==='/api/admin/songs'&&method==='POST'){const p=await body(request);const title=clean(p.title,160),slug=slugify(p.slug||title),artist=clean(p.artist,120);if(!title||!slug||!artist)return json({error:'Title, slug and artist are required'},400);try{const r=await env.DB.prepare('INSERT INTO songs(title,slug,artist,artist_slug,language,category,song_key,capo,tempo,strumming,lyrics,chords,media_json,seo_title,meta_description,tags,status,featured) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(title,slug,artist,slugify(p.artistSlug||artist),clean(p.language,30)||'Bangla',clean(p.category,40)||'Bangla',clean(p.key,20),clean(p.capo,40),clean(p.tempo,30),clean(p.strumming,120),clean(p.lyrics,50000),clean(p.chords,50000),JSON.stringify(parseMedia(p.media)),clean(p.seoTitle,160),clean(p.metaDescription,300),clean(p.tags,500),p.status==='published'?'published':'draft',p.featured?1:0).run();return json({ok:true,id:r.meta.last_row_id,slug},201);}catch(e){return json({error:'Slug must be unique'},409);}}
  const sm=path.match(/^\/api\/admin\/songs\/(\d+)$/);if(sm&&method==='PUT'){const p=await body(request),id=Number(sm[1]);await env.DB.prepare('UPDATE songs SET title=?,slug=?,artist=?,artist_slug=?,language=?,category=?,song_key=?,capo=?,tempo=?,strumming=?,lyrics=?,chords=?,media_json=?,seo_title=?,meta_description=?,tags=?,status=?,featured=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(clean(p.title,160),slugify(p.slug||p.title),clean(p.artist,120),slugify(p.artistSlug||p.artist),clean(p.language,30),clean(p.category,40),clean(p.key,20),clean(p.capo,40),clean(p.tempo,30),clean(p.strumming,120),clean(p.lyrics,50000),clean(p.chords,50000),JSON.stringify(parseMedia(p.media)),clean(p.seoTitle,160),clean(p.metaDescription,300),clean(p.tags,500),p.status==='published'?'published':'draft',p.featured?1:0,id).run();return json({ok:true});}
  if(sm&&method==='DELETE'){await env.DB.prepare('DELETE FROM songs WHERE id=?').bind(Number(sm[1])).run();return json({ok:true});}
  if(path==='/api/admin/comments'&&method==='GET'){const rows=await env.DB.prepare('SELECT comments.*,songs.title song_title FROM comments JOIN songs ON songs.id=comments.song_id ORDER BY comments.created_at DESC').all();return json(rows.results);}
  const cm=path.match(/^\/api\/admin\/comments\/(\d+)$/);if(cm&&method==='PATCH'){const p=await body(request);if(!['approved','hidden'].includes(p.status))return json({error:'Invalid status'},400);await env.DB.prepare('UPDATE comments SET status=? WHERE id=?').bind(p.status,Number(cm[1])).run();return json({ok:true});}if(cm&&method==='DELETE'){await env.DB.prepare('DELETE FROM comments WHERE id=?').bind(Number(cm[1])).run();return json({ok:true});}
  if(path==='/api/admin/requests'&&method==='GET'){const rows=await env.DB.prepare('SELECT * FROM requests ORDER BY created_at DESC').all();return json(rows.results);}
  const rm=path.match(/^\/api\/admin\/requests\/(\d+)$/);if(rm&&method==='PATCH'){const p=await body(request);if(!['pending','reviewed','done'].includes(p.status))return json({error:'Invalid status'},400);await env.DB.prepare('UPDATE requests SET status=? WHERE id=?').bind(p.status,Number(rm[1])).run();return json({ok:true});}if(rm&&method==='DELETE'){await env.DB.prepare('DELETE FROM requests WHERE id=?').bind(Number(rm[1])).run();return json({ok:true});}
 }
 return json({error:'Not found'},404);
}

export async function onRequest(context){const {request,env}=context;const url=new URL(request.url),path=url.pathname.replace(/\/$/,'')||'/';try{if(path.startsWith('/api/'))return api(request,env,path);const sm=path.match(/^\/songs\/([^/]+)$/);if(sm)return songPage(env,decodeURIComponent(sm[1]));const am=path.match(/^\/artists\/([^/]+)$/);if(am)return artistPage(env,decodeURIComponent(am[1]));if(path==='/sitemap.xml'){const rows=await env.DB.prepare("SELECT slug,artist_slug,updated_at FROM songs WHERE status='published'").all();const urls=new Map([[SITE+'/',null],[SITE+'/about.html',null],[SITE+'/contact.html',null]]);for(const s of rows.results){urls.set(`${SITE}/songs/${s.slug}/`,s.updated_at);urls.set(`${SITE}/artists/${s.artist_slug}/`,null);}const xml=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...urls].map(([loc,last])=>`<url><loc>${esc(loc)}</loc>${last?`<lastmod>${esc(last.slice(0,10))}</lastmod>`:''}</url>`).join('')}</urlset>`;return new Response(xml,{headers:{'content-type':'application/xml; charset=utf-8'}});}return context.next();}catch(e){console.error(e);return path.startsWith('/api/')?json({error:'Service temporarily unavailable'},500):new Response('Service temporarily unavailable',{status:500});}}
