const extra=document.createElement('link');extra.rel='stylesheet';extra.href='/enhancements.css';document.head.append(extra);
const $=s=>document.querySelector(s),esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let songs=[];
async function call(url,options={}){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}}),d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{status:r.status});return d}
async function load(){try{const [stats,allSongs,comments,requests]=await Promise.all([call('/api/admin/dashboard'),call('/api/admin/songs'),call('/api/admin/comments'),call('/api/admin/requests')]);$('#loginPanel').hidden=true;$('#adminPanel').hidden=false;songs=allSongs;$('#stats').innerHTML=[['Total songs',stats.totalSongs],['Total comments',stats.totalComments],['Pending comments',stats.pendingComments],['Total requests',stats.totalRequests],['Pending requests',stats.pendingRequests],['Average rating',stats.averageRatings||'0']].map(x=>`<article class="stat"><strong>${esc(x[1])}</strong><span>${x[0]}</span></article>`).join('');$('#songList').innerHTML=allSongs.map(s=>`<article class="admin-item"><div><strong>${esc(s.title)}</strong><p>${esc(s.artist)} · ${esc(s.status)}${s.featured?' · Featured':''}</p></div><div class="item-actions"><a class="btn" href="/songs/${esc(s.slug)}/" target="_blank">View</a><button class="btn edit-song" data-id="${s.id}">Edit</button><button class="btn danger delete-song" data-id="${s.id}">Delete</button></div></article>`).join('')||'<p class="muted">No songs.</p>';$('#commentList').innerHTML=comments.map(c=>`<article class="admin-item"><div><strong>${esc(c.name)} on ${esc(c.song_title)}</strong><p>${esc(c.comment)}</p><small>${esc(c.status)} · ${esc(c.created_at)}</small></div><div class="item-actions"><button class="btn comment-state" data-id="${c.id}" data-status="approved">Approve</button><button class="btn comment-state" data-id="${c.id}" data-status="hidden">Hide</button><button class="btn danger delete-comment" data-id="${c.id}">Delete</button></div></article>`).join('')||'<p class="muted">No comments.</p>';$('#requestList').innerHTML=requests.map(r=>`<article class="admin-item"><div><strong>${esc(r.type)} · ${esc(r.name)}</strong><p>${esc(r.song_name)} ${esc(r.message)}</p>${r.relevant_url?`<a href="${esc(r.relevant_url)}" target="_blank" rel="noopener">Relevant link</a>`:''}<small>${esc(r.status)} · ${esc(r.created_at)}</small></div><div class="item-actions"><button class="btn request-state" data-id="${r.id}" data-status="reviewed">Reviewed</button><button class="btn request-state" data-id="${r.id}" data-status="done">Done</button><button class="btn danger delete-request" data-id="${r.id}">Delete</button></div></article>`).join('')||'<p class="muted">No requests.</p>';bind()}catch(e){if(e.status!==401)$('#loginStatus').textContent=e.message}}
function bind(){$$('.edit-song').forEach(b=>b.onclick=()=>openSong(songs.find(s=>s.id==b.dataset.id)));$$('.delete-song').forEach(b=>b.onclick=()=>remove(`/api/admin/songs/${b.dataset.id}`,'Delete this song?'));$$('.delete-comment').forEach(b=>b.onclick=()=>remove(`/api/admin/comments/${b.dataset.id}`,'Delete this comment?'));$$('.delete-request').forEach(b=>b.onclick=()=>remove(`/api/admin/requests/${b.dataset.id}`,'Delete this request?'));$$('.comment-state').forEach(b=>b.onclick=()=>patch(`/api/admin/comments/${b.dataset.id}`,{status:b.dataset.status}));$$('.request-state').forEach(b=>b.onclick=()=>patch(`/api/admin/requests/${b.dataset.id}`,{status:b.dataset.status}))}
function $$(s){return document.querySelectorAll(s)}async function patch(url,data){await call(url,{method:'PATCH',body:JSON.stringify(data)});load()}async function remove(url,msg){if(confirm(msg)){await call(url,{method:'DELETE'});load()}}
function openSong(s={}){const f=$('#songForm');f.reset();$('#songId').value=s.id||'';$('#dialogTitle').textContent=s.id?'Edit Song':'Add Song';for(const n of ['title','slug','artist','language','category','country','musicBy','lyricsBy','sourceTitle','posterUrl','pronunciation','key','capo','tempo','strumming','lyrics','chords','seoTitle','metaDescription','tags','status']){const map={seoTitle:'seo_title',metaDescription:'meta_description',musicBy:'music_by',lyricsBy:'lyrics_by',sourceTitle:'source_title',posterUrl:'poster_url'};if(f.elements[n])f.elements[n].value=s[map[n]||n]||''}f.elements.media.value=JSON.stringify(s.media||[],null,2);f.elements.featured.checked=Boolean(s.featured);$('#songDialog').showModal()}
const language=$('#songForm').elements.language,languageInput=document.createElement('input');languageInput.name='language';languageInput.setAttribute('list','languageOptions');languageInput.placeholder='Bangla, Hindi, Urdu...';language.replaceWith(languageInput);languageInput.insertAdjacentHTML('afterend','<datalist id="languageOptions"><option value="Bangla"><option value="Hindi"><option value="English"><option value="Urdu"></datalist>');const category=$('#songForm').elements.category.closest('label');category.insertAdjacentHTML('afterend','<label>Country<input name="country"></label><label>Music by<input name="musicBy"></label><label>Lyrics by<input name="lyricsBy"></label><label>Album / Film / Drama / Source<input name="sourceTitle"></label><label class="wide">Poster image URL<input name="posterUrl" type="url" placeholder="Google Drive public link or direct image URL"></label>');const lyricsField=$('#songForm').elements.lyrics.closest('label'),chordsField=$('#songForm').elements.chords.closest('label');lyricsField.hidden=true;chordsField.childNodes[0].nodeValue='Lyrics with Chords, for example (Em)Jaan-E-Tamanna ';
chordsField.childNodes[0].nodeValue='Lyrics & Chords ';chordsField.querySelector('textarea').placeholder='কথার যেখানে chord শুরু হবে সেখানে (Em), (C), (G7) এভাবে লিখুন';chordsField.insertAdjacentHTML('afterend','<label class="wide">Pronunciation / Transliteration<textarea name="pronunciation" rows="8" placeholder="Urdu/Hindi হলে বাংলা উচ্চারণ, বাংলা হলে English pronunciation"></textarea></label>');
const pronunciationField=$('#songForm').elements.pronunciation.closest('label');pronunciationField.insertAdjacentHTML('beforeend','<span class="pronunciation-actions"><button class="btn" id="generatePronunciation" type="button">Generate pronunciation</button><small id="pronunciationStatus" class="form-note" aria-live="polite"></small></span>');
const chordToken=/([\[(][A-G](?:#|b)?(?:m|maj|min|sus|dim|aug|add)?\d*(?:\/[A-G](?:#|b)?)?[\])])/g;
const bnToLatinMap={'অ':'o','আ':'a','ই':'i','ঈ':'i','উ':'u','ঊ':'u','ঋ':'ri','এ':'e','ঐ':'oi','ও':'o','ঔ':'ou','ক':'k','খ':'kh','গ':'g','ঘ':'gh','ঙ':'ng','চ':'ch','ছ':'chh','জ':'j','ঝ':'jh','ঞ':'n','ট':'t','ঠ':'th','ড':'d','ঢ':'dh','ণ':'n','ত':'t','থ':'th','দ':'d','ধ':'dh','ন':'n','প':'p','ফ':'ph','ব':'b','ভ':'bh','ম':'m','য':'j','র':'r','ল':'l','শ':'sh','ষ':'sh','স':'s','হ':'h','ড়':'r','ঢ়':'rh','য়':'y','ৎ':'t','ং':'ng','ঃ':'h','ঁ':'n','া':'a','ি':'i','ী':'i','ু':'u','ূ':'u','ৃ':'ri','ে':'e','ৈ':'oi','ো':'o','ৌ':'ou','্':''};
function banglaToLatin(text){return [...text].map(c=>bnToLatinMap[c]??c).join('').replace(/([bcdfghjklmnpqrstvwxyz])(?=[bcdfghjklmnpqrstvwxyz]|\b)/gi,'$1o')}
const latinSounds=[['chh','ছ'],['tth','ঠ'],['ddh','ঢ'],['kh','খ'],['gh','ঘ'],['ch','চ'],['jh','ঝ'],['th','থ'],['dh','ধ'],['ph','ফ'],['bh','ভ'],['sh','শ'],['ng','ং'],['aa','া'],['ee','ি'],['ii','ি'],['oo','ু'],['ou','ৌ'],['oi','ৈ'],['ai','ৈ'],['a','া'],['i','ি'],['e','ে'],['u','ু'],['o','ো'],['k','ক'],['g','গ'],['j','জ'],['t','ত'],['d','দ'],['n','ন'],['p','প'],['f','ফ'],['b','ব'],['v','ভ'],['m','ম'],['y','য়'],['r','র'],['l','ল'],['s','স'],['h','হ'],['w','ও'],['q','ক'],['x','ক্স'],['z','জ']];
function latinWordToBangla(word){let out='',i=0;const lower=word.toLowerCase();while(i<lower.length){let hit=false;for(const [roman,bn] of latinSounds){if(lower.startsWith(roman,i)){out+=bn;i+=roman.length;hit=true;break}}if(!hit)out+=word[i++]}return out.replace(/^া/,'আ').replace(/^ি/,'ই').replace(/^ু/,'উ').replace(/^ে/,'এ').replace(/^ো/,'ও').replace(/([ক-হড়ঢ়য়])া(?=[ক-হড়ঢ়য়]|$)/g,'$1')}
function latinToBangla(text){return text.replace(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g,word=>word.split(/(['’-])/).map(part=>/[A-Za-z]/.test(part)?latinWordToBangla(part):part).join(''))}
function generatePronunciation(source){const isChord=part=>/^[\[(][A-G](?:#|b)?(?:m|maj|min|sus|dim|aug|add)?\d*(?:\/[A-G](?:#|b)?)?[\])]$/.test(part),hasBangla=/[\u0980-\u09ff]/.test(source.replace(chordToken,''));return source.split(chordToken).map(part=>isChord(part)?part:(hasBangla?banglaToLatin(part):latinToBangla(part))).join('')}
$('#generatePronunciation').onclick=()=>{const source=$('#songForm').elements.chords.value.trim(),status=$('#pronunciationStatus');if(!source){status.textContent='আগে Lyrics & Chords লিখুন।';return}const target=$('#songForm').elements.pronunciation;if(target.value.trim()&&!confirm('বর্তমান pronunciation বদলে নতুন draft তৈরি করবেন?'))return;target.value=generatePronunciation(source);status.textContent='Draft তৈরি হয়েছে। দেখে প্রয়োজনমতো ঠিক করে নিন।';target.focus()};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await call('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';load()}catch(err){$('#loginStatus').textContent=err.message}};
$('#logout').onclick=async()=>{await call('/api/admin/logout',{method:'POST'});location.reload()};$('#newSong').onclick=()=>openSong();$('#closeDialog').onclick=()=>$('#songDialog').close();
$('#songForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=$('#songId').value,data=Object.fromEntries(new FormData(f));data.featured=f.elements.featured.checked;try{data.media=JSON.parse(data.media||'[]');await call(id?`/api/admin/songs/${id}`:'/api/admin/songs',{method:id?'PUT':'POST',body:JSON.stringify(data)});$('#songDialog').close();load()}catch(err){$('#songStatus').textContent=err.message}};
$$('.admin-tabs button').forEach(b=>b.onclick=()=>{$$('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));for(const n of ['songs','comments','requests'])$('#'+n+'Tab').hidden=n!==b.dataset.tab});load();
