const extra=document.createElement('link');extra.rel='stylesheet';extra.href='/enhancements.css';document.head.append(extra);
const $=s=>document.querySelector(s),esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let songs=[];
async function call(url,options={}){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}}),d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{status:r.status});return d}
async function load(){try{const [stats,allSongs,comments,requests]=await Promise.all([call('/api/admin/dashboard'),call('/api/admin/songs'),call('/api/admin/comments'),call('/api/admin/requests')]);$('#loginPanel').hidden=true;$('#adminPanel').hidden=false;songs=allSongs;$('#stats').innerHTML=[['Total songs',stats.totalSongs],['Total comments',stats.totalComments],['Pending comments',stats.pendingComments],['Total requests',stats.totalRequests],['Pending requests',stats.pendingRequests],['Average rating',stats.averageRatings||'0']].map(x=>`<article class="stat"><strong>${esc(x[1])}</strong><span>${x[0]}</span></article>`).join('');$('#songList').innerHTML=allSongs.map(s=>`<article class="admin-item"><div><strong>${esc(s.title)}</strong><p>${esc(s.artist)} · ${esc(s.status)}${s.featured?' · Featured':''}</p></div><div class="item-actions"><a class="btn" href="/songs/${esc(s.slug)}/" target="_blank">View</a><button class="btn edit-song" data-id="${s.id}">Edit</button><button class="btn danger delete-song" data-id="${s.id}">Delete</button></div></article>`).join('')||'<p class="muted">No songs.</p>';$('#commentList').innerHTML=comments.map(c=>`<article class="admin-item"><div><strong>${esc(c.name)} on ${esc(c.song_title)}</strong><p>${esc(c.comment)}</p><small>${esc(c.status)} · ${esc(c.created_at)}</small></div><div class="item-actions"><button class="btn comment-state" data-id="${c.id}" data-status="approved">Approve</button><button class="btn comment-state" data-id="${c.id}" data-status="hidden">Hide</button><button class="btn danger delete-comment" data-id="${c.id}">Delete</button></div></article>`).join('')||'<p class="muted">No comments.</p>';$('#requestList').innerHTML=requests.map(r=>`<article class="admin-item"><div><strong>${esc(r.type)} · ${esc(r.name)}</strong><p>${esc(r.song_name)} ${esc(r.message)}</p>${r.relevant_url?`<a href="${esc(r.relevant_url)}" target="_blank" rel="noopener">Relevant link</a>`:''}<small>${esc(r.status)} · ${esc(r.created_at)}</small></div><div class="item-actions"><button class="btn request-state" data-id="${r.id}" data-status="reviewed">Reviewed</button><button class="btn request-state" data-id="${r.id}" data-status="done">Done</button><button class="btn danger delete-request" data-id="${r.id}">Delete</button></div></article>`).join('')||'<p class="muted">No requests.</p>';bind()}catch(e){if(e.status!==401)$('#loginStatus').textContent=e.message}}
function bind(){$$('.edit-song').forEach(b=>b.onclick=()=>openSong(songs.find(s=>s.id==b.dataset.id)));$$('.delete-song').forEach(b=>b.onclick=()=>remove(`/api/admin/songs/${b.dataset.id}`,'Delete this song?'));$$('.delete-comment').forEach(b=>b.onclick=()=>remove(`/api/admin/comments/${b.dataset.id}`,'Delete this comment?'));$$('.delete-request').forEach(b=>b.onclick=()=>remove(`/api/admin/requests/${b.dataset.id}`,'Delete this request?'));$$('.comment-state').forEach(b=>b.onclick=()=>patch(`/api/admin/comments/${b.dataset.id}`,{status:b.dataset.status}));$$('.request-state').forEach(b=>b.onclick=()=>patch(`/api/admin/requests/${b.dataset.id}`,{status:b.dataset.status}))}
function $$(s){return document.querySelectorAll(s)}async function patch(url,data){await call(url,{method:'PATCH',body:JSON.stringify(data)});load()}async function remove(url,msg){if(confirm(msg)){await call(url,{method:'DELETE'});load()}}
function openSong(s={}){const f=$('#songForm');f.reset();$('#songId').value=s.id||'';$('#dialogTitle').textContent=s.id?'Edit Song':'Add Song';for(const n of ['title','slug','artist','language','category','key','capo','tempo','strumming','lyrics','chords','seoTitle','metaDescription','tags','status']){const map={seoTitle:'seo_title',metaDescription:'meta_description'};if(f.elements[n])f.elements[n].value=s[map[n]||n]||''}f.elements.media.value=JSON.stringify(s.media||[],null,2);f.elements.featured.checked=Boolean(s.featured);$('#songDialog').showModal()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await call('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';load()}catch(err){$('#loginStatus').textContent=err.message}};
$('#logout').onclick=async()=>{await call('/api/admin/logout',{method:'POST'});location.reload()};$('#newSong').onclick=()=>openSong();$('#closeDialog').onclick=()=>$('#songDialog').close();
$('#songForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=$('#songId').value,data=Object.fromEntries(new FormData(f));data.featured=f.elements.featured.checked;try{data.media=JSON.parse(data.media||'[]');await call(id?`/api/admin/songs/${id}`:'/api/admin/songs',{method:id?'PUT':'POST',body:JSON.stringify(data)});$('#songDialog').close();load()}catch(err){$('#songStatus').textContent=err.message}};
$$('.admin-tabs button').forEach(b=>b.onclick=()=>{$$('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));for(const n of ['songs','comments','requests'])$('#'+n+'Tab').hidden=n!==b.dataset.tab});load();
