const $=s=>document.querySelector(s),grid=$('#songGrid'),search=$('#searchInput'),count=$('#songCount');
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let songs=[];
function deviceId(){let id=localStorage.getItem('akb_device');if(!id){id=crypto.randomUUID();localStorage.setItem('akb_device',id)}return id}
function render(list){count.textContent=`${list.length} গান`;grid.innerHTML=list.length?list.map(s=>`<a class="song-card" href="/songs/${encodeURIComponent(s.slug)}/"><h3>${esc(s.title)}</h3><p>${esc(s.artist)}</p><div class="chips"><span class="chip">Key ${esc(s.key||'N/A')}</span><span class="chip">${esc(s.language)}</span>${s.capo?`<span class="chip">${esc(s.capo)}</span>`:''}</div></a>`).join(''):'<div class="empty">কোনো গান পাওয়া যায়নি।</div>'}
function filter(){const q=search.value.trim().toLowerCase();render(!q?songs:songs.filter(s=>`${s.title} ${s.artist} ${s.lyrics} ${s.chords} ${s.tags}`.toLowerCase().includes(q)))}
fetch('/api/songs').then(r=>r.ok?r.json():Promise.reject()).then(data=>{songs=data;const q=new URLSearchParams(location.search).get('q');if(q)search.value=q;filter()}).catch(()=>grid.innerHTML='<div class="empty">গানের তালিকা এখন লোড করা যাচ্ছে না।</div>');
search.addEventListener('input',filter);$('#year').textContent=new Date().getFullYear();deviceId();
$('#requestForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=$('#requestStatus'),button=form.querySelector('button');button.disabled=true;status.textContent='পাঠানো হচ্ছে...';const payload={name:$('#requestName').value,type:$('#requestType').value,songName:$('#requestSong').value,message:$('#requestMessage').value,relevantUrl:$('#requestUrl').value};try{const r=await fetch('/api/requests',{method:'POST',headers:{'content-type':'application/json','x-device-id':deviceId()},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error);form.reset();status.textContent='আপনার বার্তাটি পাওয়া গেছে। ধন্যবাদ।'}catch(err){status.textContent=err.message||'পাঠানো যায়নি। পরে আবার চেষ্টা করুন।'}finally{button.disabled=false}});
