const themeScript=document.createElement('script');themeScript.src='/theme.js';themeScript.defer=true;document.head.append(themeScript);const root=document.getElementById('songRoot'),chromatic=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const intentText=`${new URLSearchParams(location.search).get('view')||''} ${document.referrer||''}`.toLowerCase();let shift=0,showChords=/(chord|কর্ড)/.test(intentText)&&!/(lyrics|লিরিক্স)/.test(intentText),fontSize=18,song=JSON.parse(root.dataset.song||'null');
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function deviceId(){let id=localStorage.getItem('akb_device');if(!id){id=crypto.randomUUID();localStorage.setItem('akb_device',id)}return id}
function transposeChord(chord,steps){return chord.replace(/[A-G](?:#|b)?/g,n=>{const flat={Db:'C#',Eb:'D#',Gb:'F#',Ab:'G#',Bb:'A#'}[n]||n,idx=chromatic.indexOf(flat);return idx<0?n:chromatic[(idx+steps+120)%12]})}
const chordPattern=/[\[(]([A-G](?:#|b)?(?:m|maj|min|sus|dim|aug|add)?\d*(?:\/[A-G](?:#|b)?)?)[\])]/g;
function chordedLine(line){let out='',last=0,m,hasChord=false;chordPattern.lastIndex=0;while((m=chordPattern.exec(line))){hasChord=true;out+=esc(line.slice(last,m.index));out+=`<span class="chord-anchor" aria-hidden="true"><span class="chord-label">${esc(transposeChord(m[1],shift))}</span></span>`;last=chordPattern.lastIndex}out+=esc(line.slice(last));return `<div class="lyric-line${hasChord?' has-chords':''}">${out||'&nbsp;'}</div>`}
function lyrics(source=showChords?song.chords:song.lyrics){return String(source||'').split('\n').map(line=>showChords?chordedLine(line):`<div class="lyric-line">${esc(line.replace(chordPattern,''))||'&nbsp;'}</div>`).join('')}
function comments(){return song.comments?.length?song.comments.map(c=>`<article class="comment"><strong>${esc(c.name||'Anonymous')}</strong><p>${esc(c.comment)}</p></article>`).join(''):'<p class="muted">এখনও অনুমোদিত মন্তব্য নেই।</p>'}
function render(){const has=Boolean(song.chords?.trim()),key=transposeChord(song.key||'',shift);root.innerHTML=`<h1 class="song-title">${esc(song.title)}</h1><p class="song-meta"><a href="/artists/${esc(song.artist_slug)}/">${esc(song.artist)}</a> · Key ${esc(key||'N/A')} ${song.capo?`· ${esc(song.capo)}`:''} · ${esc(song.language)}</p><div class="toolbar"><label class="toggle-control ${!has?'disabled':''}"><input id="chordToggle" type="checkbox" ${showChords?'checked':''} ${!has?'disabled':''}><span>Show Chords</span></label><button class="btn" id="down" ${!has?'disabled':''}>− Transpose</button><button class="btn" id="reset" ${!has?'disabled':''}>মূল Key</button><button class="btn" id="up" ${!has?'disabled':''}>+ Transpose</button><button class="btn" id="smaller" aria-label="লেখা ছোট করুন">A−</button><button class="btn" id="larger" aria-label="লেখা বড় করুন">A+</button></div><section class="lyrics-box"><div class="section-head compact"><h2>${showChords?'Lyrics & Chords':'Lyrics'}</h2></div>${showChords&&song.strumming?`<p><strong>Strumming:</strong> ${esc(song.strumming)}</p>`:''}${song.tempo?`<p class="muted">Tempo: ${esc(song.tempo)}</p>`:''}<div class="lyrics" style="font-size:${fontSize}px">${lyrics()}</div></section><section class="feedback-box"><h2>Rating & Comment</h2><p id="ratingSummary" class="rating-summary">${song.rating?.count?`${song.rating.average} / 5 (${song.rating.count})`:'এখনও কোনো rating নেই'}</p><div class="rating-row" aria-label="এই গানকে rating দিন">${[1,2,3,4,5].map(n=>`<button class="star-btn" data-rating="${n}" aria-label="${n} star">★</button>`).join('')}</div><form id="commentForm" class="stack-form"><input id="commentName" maxlength="60" placeholder="Name (optional)"><textarea id="commentText" maxlength="800" required placeholder="মন্তব্য লিখুন..."></textarea><button class="primary-btn">Post Comment</button><p id="commentStatus" class="form-note" aria-live="polite"></p></form><div class="comments">${comments()}</div><p class="form-note">নাম না দিলে Anonymous হিসেবে জমা হবে। মন্তব্য অনুমোদনের পর প্রকাশিত হবে।</p></section>`;
 document.getElementById('chordToggle').onchange=e=>{showChords=e.target.checked;render()};document.getElementById('down').onclick=()=>{shift--;render()};document.getElementById('up').onclick=()=>{shift++;render()};document.getElementById('reset').onclick=()=>{shift=0;render()};document.getElementById('smaller').onclick=()=>{fontSize=Math.max(16,fontSize-1);render()};document.getElementById('larger').onclick=()=>{fontSize=Math.min(34,fontSize+1);render()};
 document.querySelectorAll('.star-btn').forEach(b=>b.onclick=async()=>{const r=await fetch(`/api/songs/${encodeURIComponent(song.slug)}/rating`,{method:'POST',headers:{'content-type':'application/json','x-device-id':deviceId()},body:JSON.stringify({rating:Number(b.dataset.rating)})}),d=await r.json();document.getElementById('ratingSummary').textContent=r.ok?`${d.average} / 5 (${d.count})`:d.error});
 document.getElementById('commentForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button'),status=document.getElementById('commentStatus');button.disabled=true;const r=await fetch(`/api/songs/${encodeURIComponent(song.slug)}/comments`,{method:'POST',headers:{'content-type':'application/json','x-device-id':deviceId()},body:JSON.stringify({name:document.getElementById('commentName').value,comment:document.getElementById('commentText').value})}),d=await r.json();status.textContent=r.ok?'মন্তব্য জমা হয়েছে। অনুমোদনের পর দেখা যাবে।':d.error;if(r.ok)e.currentTarget.reset();button.disabled=false};
}
const baseRender=render;render=()=>{baseRender();const rows=[['Song',song.title],['Singer',song.artist],['Music',song.music_by],['Lyrics',song.lyrics_by],['Album / Film / Drama / Source',song.source_title],['Language',song.language],['Country',song.country]].filter(x=>x[1]);if(rows.length||song.poster_url)document.querySelector('.toolbar').insertAdjacentHTML('beforebegin',`<section class="song-details"><dl>${rows.map(x=>`<div><dt>${esc(x[0])}</dt><dd>${esc(x[1])}</dd></div>`).join('')}</dl>${song.poster_url?`<img src="${esc(song.poster_url)}" alt="${esc(song.title)} poster" loading="lazy" referrerpolicy="no-referrer">`:''}</section>`)};
let pronunciationMode=/(pronunciation|উচ্চারণ)/.test(intentText);const modeRender=render;render=()=>{modeRender();const chordToggle=document.getElementById('chordToggle'),controls=['down','reset','up'].map(id=>document.getElementById(id));controls.forEach(el=>el.hidden=!showChords);if(chordToggle)chordToggle.onchange=e=>{showChords=e.target.checked;render()};if(song.pronunciation){const button=document.createElement('button');button.className='btn';button.type='button';button.textContent=song.language==='Bangla'?'English Pronunciation':'বাংলা উচ্চারণ';button.setAttribute('aria-pressed',String(pronunciationMode));button.onclick=()=>{pronunciationMode=!pronunciationMode;render()};document.querySelector('.toolbar').prepend(button);if(pronunciationMode){document.querySelector('.lyrics').innerHTML=lyrics(song.pronunciation);document.querySelector('.lyrics-box h2').textContent=`${button.textContent}${showChords?' & Chords':''}`}}const note=document.querySelector('.feedback-box > .form-note:last-child');if(note)note.remove()};
if(song){deviceId();render()}else{const legacy=new URLSearchParams(location.search).get('slug');if(legacy)fetch('/api/songs/'+encodeURIComponent(legacy)).then(r=>r.json()).then(data=>{song=data;history.replaceState({},'',`/songs/${encodeURIComponent(song.slug)}/`);deviceId();render()}).catch(()=>root.innerHTML='<div class="empty">গানটি পাওয়া যায়নি।</div>');else root.innerHTML='<div class="empty">গানটি পাওয়া যায়নি।</div>'}
