ALTER TABLE songs ADD COLUMN country TEXT NOT NULL DEFAULT '';
ALTER TABLE songs ADD COLUMN music_by TEXT NOT NULL DEFAULT '';
ALTER TABLE songs ADD COLUMN lyrics_by TEXT NOT NULL DEFAULT '';
ALTER TABLE songs ADD COLUMN source_title TEXT NOT NULL DEFAULT '';
ALTER TABLE songs ADD COLUMN poster_url TEXT NOT NULL DEFAULT '';
